project:
  type: website
  output-dir: site
  render:
    - "*.qmd"
    - "wiki/**/*.qmd"
    - "notebooks/index.qmd"
    - "notebooks/**/*.ipynb"

website:
  title: "Ian's Local Wiki"
  sidebar:
    - title: "Wiki"
      style: "docked"
      search: true
      contents:
        - section: "Linux"
          contents:
            - wiki/linux/index.qmd
            - wiki/linux/nginx.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: wiki/index.qmd
        text: Wiki
      - href: notebooks/index.qmd
        text: Notebooks
      - href: /mw/
        text: MediaWiki
      - href: /blog/
        text: Blog
  breadcrumbs: true  
  search: true
  page-navigation: true
  page-footer: |
    <small>
      Deployed {{< meta commit >}} at {{< meta date >}}
    </small>

metadata-files: 
  - _deploy.yml

format:
  html:
    toc: true
    code-fold: true

execute:
  freeze: true
