project:
  type: website
  output-dir: ../site

website:
  title: "Ian's Local Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: wiki/index.qmd
        text: Wiki
      - href: notebooks/index.qmd
        text: Notebooks
      - href: /mw/
        text: MediaWiki
  search: true

format:
  html:
    toc: true
    code-fold: true

execute:
  freeze: true
