project:
  type: website
  output-dir: site
  render:
    - "*.qmd"
    - "wiki/**/*.qmd"
    - "notebooks/index.qmd"
    - "notebooks/**/*.ipynb"

website:
  title: "Ian's Local Wiki"
  sidebar:
    - title: "Wiki"
      style: "docked"
      search: true
      contents:
        - section: "Programming"
        - contents:
          - href: wiki/Programming/index.qmd
            text: "Programming_sb"
        - section: "Linux"
        - contents:
          - href: wiki/Linux/index.qmd
            text: "Linux"
          - section: "Services & APIs"
            - contents:
                - href: wiki/Linux/Services_APIs/index.qmd
                  text: "Services & APIs"
          - section: "Notebooks"
        - contents:
          - href: notebooks/index.qmd
            text: "Notebooks"      
        - section: "Raspberry Pi"
        - contents:
          - href: wiki/Raspberry_Pi/index.qmd
            text: "Raspberry Pi"


        #     text: "Linux Commands"
        #   - href: wiki/linux/shell-scripting.qmd

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: wiki/Programming/index.qmd
        text: Programming
      - href: wiki/Linux/index.qmd
        text: Linux
      - href: notebooks/index.qmd
        text: Notebooks
      - href: /mw/
        text: MediaWiki
      - href: /blog/
        text: Blog
      - href: http://raspian.local:4080
        text: Chat
  bread-crumbs: true  
  search: true
  page-navigation: true
  page-footer: |
    <small>
      Deployed {{< meta commit >}} at {{< meta date >}}
    </small>

metadata-files: 
  - _deploy.yml

format:
  html:
    toc: true
    code-fold: true

execute:
  freeze: true
